# Generated by Django 2.1 on 2018-10-31 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EklallsimbVw',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('surname', models.CharField(db_column='surname', db_index=True, max_length=100)),
                ('firstname', models.CharField(db_column='firstname', db_index=True, max_length=100)),
                ('fathername', models.CharField(db_column='fathername', db_index=True, max_length=100)),
                ('comments', models.CharField(db_column='comments', max_length=100)),
                ('toposeklogisid', models.IntegerField(db_column='toposEklogisID')),
                ('toposeklogis', models.CharField(db_column='toposEklogis', max_length=100)),
                ('eidoskoinotitas', models.IntegerField(blank=True, db_column='eidosKoinotitas', null=True)),
                ('sindid', models.IntegerField(blank=True, db_column='sindID', db_index=True, null=True)),
                ('sindiasmos', models.CharField(blank=True, db_column='sindiasmos', db_index=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'EKL_ALLSIMB_VW',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EklKatametrimenaBVw',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('eklid', models.IntegerField(db_column='eklID')),
                ('katametrimenab', models.BigIntegerField(db_column='katametrimenaB')),
            ],
            options={
                'db_table': 'EKL_KATAMETRIMENA_B_VW',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EklKatametrimenaPsifoiVw',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('eklid', models.IntegerField(db_column='eklID')),
                ('katametrimena', models.BigIntegerField()),
            ],
            options={
                'db_table': 'EKL_KATAMETRIMENA_PSIFOI_VW',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EklKatametrimenaVw',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('eklid', models.IntegerField(db_column='eklID')),
                ('katametrimena', models.BigIntegerField()),
            ],
            options={
                'db_table': 'EKL_KATAMETRIMENA_VW',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EklPosostasindPerVw',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('eklid', models.IntegerField(db_column='eklID')),
                ('perid', models.IntegerField(db_column='perID')),
                ('perifereia', models.CharField(db_column='perifereia', max_length=100)),
                ('sindiasmos', models.CharField(db_column='sindiasmos', max_length=100)),
                ('shortdescr', models.CharField(db_column='shortDescr', max_length=50)),
                ('sumper', models.DecimalField(blank=True, db_column='sumPer', decimal_places=0, max_digits=32, null=True)),
                ('sumvotes', models.DecimalField(blank=True, db_column='sumVotes', decimal_places=0, max_digits=32, null=True)),
                ('posostosindiasmou', models.DecimalField(blank=True, decimal_places=2, max_digits=38, null=True)),
            ],
            options={
                'db_table': 'EKL_POSOSTASIND_PER_VW',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EklPsifoisimbVw',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('sindaa', models.CharField(blank=True, db_column='sindaa', max_length=45, null=True)),
                ('sindiasmos', models.CharField(blank=True, db_column='sindiasmos', max_length=100, null=True)),
                ('shortsind', models.CharField(blank=True, db_column='shortsind', max_length=100, null=True)),
                ('surname', models.CharField(db_index=True, max_length=100)),
                ('firstname', models.CharField(db_index=True, max_length=100)),
                ('fathername', models.CharField(db_index=True, max_length=100)),
                ('simbaa', models.CharField(db_column='simbaa', max_length=45)),
                ('toposeklogis', models.CharField(db_column='toposEklogis', max_length=100)),
                ('kentro', models.CharField(max_length=45)),
                ('eidos', models.CharField(db_column='eidos', max_length=100)),
                ('koinotita', models.CharField(max_length=100)),
                ('votes', models.IntegerField()),
            ],
            options={
                'db_table': 'EKL_PSIFOISIMB_VW',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EklSindedresKoinVw',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('eklid', models.IntegerField(db_column='eklID')),
                ('sindid', models.IntegerField(db_column='sindID')),
                ('koinid', models.IntegerField(db_column='koinID')),
                ('edresk', models.IntegerField(db_column='edresK')),
                ('edresk_ypol', models.IntegerField(db_column='edresK_Ypol')),
                ('edresk_teliko', models.IntegerField(db_column='edresK_Teliko')),
                ('ypol', models.IntegerField()),
                ('sumedres', models.DecimalField(blank=True, db_column='sumEdres', decimal_places=0, max_digits=32, null=True)),
                ('sumedresypol', models.DecimalField(blank=True, db_column='sumEdresYpol', decimal_places=0, max_digits=32, null=True)),
                ('sumedresteliko', models.DecimalField(blank=True, db_column='sumEdresTeliko', decimal_places=0, max_digits=32, null=True)),
                ('sinolo', models.IntegerField()),
                ('checkfordraw', models.IntegerField(db_column='checkForDraw')),
            ],
            options={
                'db_table': 'EKL_SINDEDRES_KOIN_VW',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EklSinolokentrwnAnaAnametrhsh',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('eklid', models.IntegerField()),
                ('plithoskentrwn', models.BigIntegerField(db_column='plithosKentrwn')),
            ],
            options={
                'db_table': 'EKL_SINOLOKENTRWN_ANA_ANAMETRHSH',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EklSumpsifodeltiaKenVw',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('eklid', models.IntegerField(db_column='eklID')),
                ('kentro', models.CharField(max_length=45)),
                ('kenid', models.IntegerField(db_column='kenID')),
                ('sumvotes', models.DecimalField(blank=True, db_column='sumVotes', decimal_places=0, max_digits=32, null=True)),
                ('sumvotesb', models.DecimalField(blank=True, db_column='sumVotesB', decimal_places=0, max_digits=32, null=True)),
            ],
            options={
                'db_table': 'EKL_SUMPSIFODELTIA_KEN_VW',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EklSumpsifodeltiaPerVw',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('eklid', models.IntegerField(db_column='eklID')),
                ('perid', models.IntegerField(db_column='perID')),
                ('sumvotes', models.DecimalField(blank=True, db_column='sumVotes', decimal_places=0, max_digits=32, null=True)),
            ],
            options={
                'db_table': 'EKL_SUMPSIFODELTIA_PER_VW',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EklSumpsifodeltiasindKenTopikoiOnlyVw',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('kentro', models.CharField(max_length=45)),
                ('votes', models.IntegerField()),
                ('votesb', models.IntegerField(db_column='votesB')),
                ('votesk', models.IntegerField(db_column='votesK')),
                ('sindiasmos', models.CharField(max_length=100)),
                ('eidos', models.IntegerField(db_column='eidos')),
            ],
            options={
                'db_table': 'EKL_SUMPSIFODELTIASINDTOPIKOIONLY_KEN_VW',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EklSumpsifodeltiasindKenVw',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('kentro', models.CharField(max_length=45)),
                ('votes', models.IntegerField()),
                ('votesb', models.IntegerField(db_column='votesB')),
                ('votesk', models.IntegerField(db_column='votesK')),
                ('sindiasmos', models.CharField(max_length=100)),
                ('eidos', models.IntegerField(db_column='eidos')),
            ],
            options={
                'db_table': 'EKL_SUMPSIFODELTIASIND_KEN_VW',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EklSumpsifodeltiasindKoinVw',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('sindiasmos', models.CharField(max_length=100)),
                ('koinid', models.IntegerField(db_column='koinID')),
                ('descr', models.CharField(db_column='descr', max_length=100)),
                ('eidos', models.IntegerField(db_column='eidos')),
                ('sumasindiasmou', models.DecimalField(blank=True, db_column='sumASindiasmou', decimal_places=0, max_digits=32, null=True)),
                ('sumbsindiasmou', models.DecimalField(blank=True, db_column='sumBSindiasmou', decimal_places=0, max_digits=32, null=True)),
                ('sumksindiasmou', models.DecimalField(blank=True, db_column='sumKSindiasmou', decimal_places=0, max_digits=32, null=True)),
                ('sumkkoinotitas', models.DecimalField(blank=True, db_column='sumkKoinotitas', decimal_places=0, max_digits=32, null=True)),
            ],
            options={
                'db_table': 'EKL_SUMPSIFODELTIASIND_KOIN_VW',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EklSumpsifodeltiasindPerVw',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('eklid', models.IntegerField(db_column='eklID')),
                ('sindid', models.IntegerField(db_column='sindID')),
                ('sindiasmos', models.CharField(db_column='sindiasmos', max_length=100)),
                ('shortdescr', models.CharField(db_column='shortDescr', max_length=50)),
                ('perifereia', models.CharField(max_length=100)),
                ('perid', models.IntegerField(db_column='perID')),
                ('sumvotes', models.DecimalField(blank=True, db_column='sumVotes', decimal_places=0, max_digits=32, null=True)),
            ],
            options={
                'db_table': 'EKL_SUMPSIFODELTIASIND_PER_VW',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EklSumpsifodeltiasindVw',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('sindiasmos', models.CharField(max_length=100)),
                ('shortdescr', models.CharField(db_column='shortDescr', max_length=50)),
                ('photo', models.ImageField(db_column='photo', null=True, upload_to='')),
                ('sumvotes', models.DecimalField(blank=True, db_column='sumVotes', decimal_places=0, max_digits=32, null=True)),
                ('sinola', models.DecimalField(blank=True, decimal_places=0, max_digits=32, null=True)),
                ('katametrimena', models.BigIntegerField(blank=True, null=True)),
                ('plithoskentrwn', models.BigIntegerField(db_column='plithosKentrwn')),
                ('posostosindiasmou', models.DecimalField(blank=True, db_column='posostoSindiasmou', decimal_places=2, max_digits=38, null=True)),
                ('posostokatametrimenwnkentrwn', models.DecimalField(blank=True, db_column='posostoKatametrimenwnKentrwn', decimal_places=2, max_digits=26, null=True)),
                ('sumvotesb', models.DecimalField(blank=True, db_column='sumVotesB', decimal_places=0, max_digits=32, null=True)),
                ('sinolab', models.DecimalField(blank=True, db_column='sinolaB', decimal_places=0, max_digits=32, null=True)),
                ('posostosindiasmoub', models.DecimalField(blank=True, db_column='posostoSindiasmouB', decimal_places=2, max_digits=38, null=True)),
                ('katametrimenab', models.BigIntegerField(blank=True, db_column='katametrimenaB', null=True)),
                ('posostokatametrimenwnkentrwnb', models.DecimalField(blank=True, db_column='posostoKatametrimenwnKentrwnB', decimal_places=2, max_digits=26, null=True)),
                ('sumvotesk', models.DecimalField(blank=True, db_column='sumVotesK', decimal_places=0, max_digits=32, null=True)),
                ('sinolak', models.DecimalField(blank=True, db_column='sinolaK', decimal_places=0, max_digits=32, null=True)),
                ('posostosindiasmouk', models.DecimalField(blank=True, db_column='posostoSindiasmouK', decimal_places=2, max_digits=38, null=True)),
                ('katametrimenak', models.BigIntegerField(blank=True, db_column='katametrimenaK', null=True)),
                ('posostokatametrimenwnkentrwnk', models.DecimalField(blank=True, db_column='posostoKatametrimenwnKentrwnK', decimal_places=2, max_digits=26, null=True)),
                ('eidos', models.IntegerField(db_column='eidos')),
            ],
            options={
                'db_table': 'EKL_SUMPSIFODELTIASIND_VW',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EklSumpsifoiKenVw',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('eklid', models.IntegerField(db_column='eklID')),
                ('kentro', models.CharField(max_length=45)),
                ('kenid', models.IntegerField(db_column='kenID')),
                ('sumvotes', models.DecimalField(blank=True, db_column='sumVotes', decimal_places=0, max_digits=32, null=True)),
            ],
            options={
                'db_table': 'EKL_SUMPSIFOI_KEN_VW',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EklSumpsifoisimbAnalytikoAnaperifereia',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('eklid', models.IntegerField(db_column='eklID')),
                ('eidos', models.CharField(max_length=20)),
                ('simbid', models.IntegerField(db_column='simbID')),
                ('eklsimbkoin_simbid', models.IntegerField(blank=True, db_column='EKLSIMBKOIN_simbID', null=True)),
                ('surname', models.CharField(max_length=100)),
                ('firstname', models.CharField(max_length=100)),
                ('fathername', models.CharField(max_length=100)),
                ('perid', models.IntegerField(db_column='perID')),
                ('perifereia', models.CharField(max_length=100)),
                ('sumvotes', models.DecimalField(blank=True, db_column='sumVotes', decimal_places=0, max_digits=32, null=True)),
                ('sindid', models.IntegerField(blank=True, db_column='sindID', null=True)),
                ('sindiasmos', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'EKL_SUMPSIFOISIMB_ANALYTIKO_ANAPERIFEREIA',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EklSumpsifoisimbKoinVw',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('eklid', models.IntegerField(db_column='eklID')),
                ('simbid', models.IntegerField(db_column='simbID')),
                ('surname', models.CharField(max_length=100)),
                ('firstname', models.CharField(max_length=100)),
                ('fathername', models.CharField(max_length=100)),
                ('toposeklogisid', models.IntegerField(db_column='toposEklogisID')),
                ('toposeklogis', models.CharField(db_column='toposEklogis', max_length=100)),
                ('eidoskoinotitas', models.IntegerField(db_column='eidosKoinotitas')),
                ('sindid', models.IntegerField(blank=True, db_column='sindID', null=True)),
                ('sindiasmos', models.CharField(blank=True, max_length=100, null=True)),
                ('sumvotes', models.DecimalField(blank=True, db_column='sumVotes', decimal_places=0, max_digits=32, null=True)),
            ],
            options={
                'db_table': 'EKL_SUMPSIFOISIMB_KOIN_VW',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EklSumpsifoisimbPerLightVw',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('eklid', models.IntegerField(db_column='eklID', db_index=True)),
                ('simbid', models.IntegerField(db_column='simbID', db_index=True)),
                ('sumvotes', models.DecimalField(blank=True, db_column='sumVotes', decimal_places=0, max_digits=32, null=True)),
            ],
            options={
                'db_table': 'EKL_SUMPSIFOISIMBPER_LIGHT_VW',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EklSumpsifoisimbPerVw',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('surname', models.CharField(max_length=100)),
                ('firstname', models.CharField(max_length=100)),
                ('fathername', models.CharField(max_length=100)),
                ('toposeklogisid', models.IntegerField(db_column='toposEklogisID')),
                ('toposeklogis', models.CharField(db_column='toposEklogis', max_length=100)),
                ('sindiasmos', models.CharField(blank=True, max_length=100, null=True)),
                ('sumvotes', models.DecimalField(blank=True, db_column='sumVotes', decimal_places=0, max_digits=32, null=True)),
            ],
            options={
                'db_table': 'EKL_SUMPSIFOISIMB_PER_VW',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EklSumpsifoisimbVw',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('eklid', models.IntegerField(db_column='eklID')),
                ('simbid', models.IntegerField(db_column='simbID')),
                ('surname', models.CharField(max_length=100)),
                ('firstname', models.CharField(max_length=100)),
                ('fathername', models.CharField(max_length=100)),
                ('toposeklogisid', models.IntegerField(db_column='toposEklogisID')),
                ('toposeklogis', models.CharField(db_column='toposEklogis', max_length=100)),
                ('eidoskoinotitas', models.IntegerField(blank=True, db_column='eidosKoinotitas', null=True)),
                ('sindiasmos', models.CharField(blank=True, max_length=100, null=True)),
                ('sumvotes', models.DecimalField(blank=True, db_column='sumVotes', decimal_places=0, max_digits=32, null=True)),
            ],
            options={
                'db_table': 'EKL_SUMPSIFOISIMB_VW',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EklSumpsifoisimbWithIdVw',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('surname', models.CharField(max_length=100)),
                ('firstname', models.CharField(max_length=100)),
                ('fathername', models.CharField(max_length=100)),
                ('toposeklogisid', models.IntegerField(db_column='toposEklogisID')),
                ('toposeklogis', models.CharField(db_column='toposEklogis', max_length=100)),
                ('eidoskoinotitas', models.IntegerField(blank=True, db_column='eidosKoinotitas', null=True)),
                ('sindiasmos', models.CharField(blank=True, max_length=100, null=True)),
                ('sumvotes', models.DecimalField(blank=True, db_column='sumVotes', decimal_places=0, max_digits=32, null=True)),
            ],
            options={
                'db_table': 'EKL_SUMPSIFOISIMB_WITHID_VW',
                'managed': False,
            },
        ),
    ]
