# Generated by Django 2.1 on 2018-08-26 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EklKatametrimenaBVw',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('eklid', models.IntegerField(db_column='eklID')),
                ('katametrimenab', models.BigIntegerField(db_column='katametrimenaB')),
            ],
            options={
                'db_table': 'EKL_KATAMETRIMENA_B_VW',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EklKatametrimenaPsifoiVw',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('eklid', models.IntegerField(db_column='eklID')),
                ('katametrimena', models.BigIntegerField()),
            ],
            options={
                'db_table': 'EKL_KATAMETRIMENA_PSIFOI_VW',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EklKatametrimenaVw',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('eklid', models.IntegerField(db_column='eklID')),
                ('katametrimena', models.BigIntegerField()),
            ],
            options={
                'db_table': 'EKL_KATAMETRIMENA_VW',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EklPosostasindPerVw',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('eklid', models.IntegerField(db_column='eklID')),
                ('perid', models.IntegerField(db_column='perID')),
                ('perifereia', models.CharField(db_column='perifereia', max_length=100)),
                ('sindiasmos', models.CharField(db_column='sindiasmos', max_length=100)),
                ('shortdescr', models.CharField(db_column='shortDescr', max_length=50)),
                ('sumper', models.DecimalField(blank=True, db_column='sumPer', decimal_places=0, max_digits=32, null=True)),
                ('sumvotes', models.DecimalField(blank=True, db_column='sumVotes', decimal_places=0, max_digits=32, null=True)),
                ('posostosindiasmou', models.DecimalField(blank=True, decimal_places=2, max_digits=38, null=True)),
            ],
            options={
                'db_table': 'EKL_POSOSTASIND_PER_VW',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EklPsifoisimbVw',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('eklid', models.IntegerField(db_column='eklID')),
                ('sindid', models.IntegerField(blank=True, db_column='sindID', null=True)),
                ('sindiasmos', models.CharField(blank=True, max_length=100, null=True)),
                ('simbid', models.IntegerField(db_column='simbID')),
                ('surname', models.CharField(max_length=100)),
                ('firstname', models.CharField(max_length=100)),
                ('fathername', models.CharField(max_length=100)),
                ('kenid', models.IntegerField(db_column='kenID')),
                ('kentro', models.CharField(max_length=45)),
                ('votes', models.IntegerField()),
            ],
            options={
                'db_table': 'EKL_PSIFOISIMB_VW',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EklSindedresKoinVw',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('eklid', models.IntegerField(db_column='eklID')),
                ('sindid', models.IntegerField(db_column='sindID')),
                ('koinid', models.IntegerField(db_column='koinID')),
                ('edresk', models.IntegerField(db_column='edresK')),
                ('edresk_ypol', models.IntegerField(db_column='edresK_Ypol')),
                ('edresk_teliko', models.IntegerField(db_column='edresK_Teliko')),
                ('ypol', models.IntegerField()),
                ('sumedres', models.DecimalField(blank=True, db_column='sumEdres', decimal_places=0, max_digits=32, null=True)),
                ('sumedresypol', models.DecimalField(blank=True, db_column='sumEdresYpol', decimal_places=0, max_digits=32, null=True)),
                ('sumedresteliko', models.DecimalField(blank=True, db_column='sumEdresTeliko', decimal_places=0, max_digits=32, null=True)),
                ('sinolo', models.IntegerField()),
                ('checkfordraw', models.IntegerField(db_column='checkForDraw')),
            ],
            options={
                'db_table': 'EKL_SINDEDRES_KOIN_VW',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EklSinolokentrwnAnaAnametrhsh',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('eklid', models.IntegerField()),
                ('plithoskentrwn', models.BigIntegerField(db_column='plithosKentrwn')),
            ],
            options={
                'db_table': 'EKL_SINOLOKENTRWN_ANA_ANAMETRHSH',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EklSumpsifodeltiaKenVw',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('eklid', models.IntegerField(db_column='eklID')),
                ('kentro', models.CharField(max_length=45)),
                ('kenid', models.IntegerField(db_column='kenID')),
                ('sumvotes', models.DecimalField(blank=True, db_column='sumVotes', decimal_places=0, max_digits=32, null=True)),
                ('sumvotesb', models.DecimalField(blank=True, db_column='sumVotesB', decimal_places=0, max_digits=32, null=True)),
            ],
            options={
                'db_table': 'EKL_SUMPSIFODELTIA_KEN_VW',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EklSumpsifodeltiaPerVw',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('eklid', models.IntegerField(db_column='eklID')),
                ('perid', models.IntegerField(db_column='perID')),
                ('sumvotes', models.DecimalField(blank=True, db_column='sumVotes', decimal_places=0, max_digits=32, null=True)),
            ],
            options={
                'db_table': 'EKL_SUMPSIFODELTIA_PER_VW',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EklSumpsifodeltiasindKenVw',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('eklid', models.IntegerField(db_column='eklID')),
                ('kenid', models.IntegerField(db_column='kenID')),
                ('kentro', models.CharField(max_length=45)),
                ('votes', models.IntegerField()),
                ('votesb', models.IntegerField(db_column='votesB')),
                ('sindid', models.IntegerField(db_column='sindID')),
                ('sindiasmos', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'EKL_SUMPSIFODELTIASIND_KEN_VW',
                'managed': False,
            },
        ),

        migrations.CreateModel(
            name='EklSumpsifodeltiasindPerVw',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('eklid', models.IntegerField(db_column='eklID')),
                ('sindid', models.IntegerField(db_column='sindID')),
                ('sindiasmos', models.CharField(db_column='sindiasmos', max_length=100)),
                ('shortdescr', models.CharField(db_column='shortDescr', max_length=50)),
                ('perifereia', models.CharField(max_length=100)),
                ('perid', models.IntegerField(db_column='perID')),
                ('sumvotes', models.DecimalField(blank=True, db_column='sumVotes', decimal_places=0, max_digits=32, null=True)),
            ],
            options={
                'db_table': 'EKL_SUMPSIFODELTIASIND_PER_VW',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EklSumpsifodeltiasindVw',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('eklid', models.IntegerField(db_column='eklID')),
                ('sindid', models.IntegerField(db_column='sindID')),
                ('sindiasmos', models.CharField(max_length=100)),
                ('shortdescr', models.CharField(db_column='shortDescr', max_length=50)),
                ('photo', models.ImageField(db_column='photo', null=True, upload_to='')),
                ('sumvotes', models.DecimalField(blank=True, db_column='sumVotes', decimal_places=0, max_digits=32, null=True)),
                ('sinola', models.DecimalField(blank=True, decimal_places=0, max_digits=32, null=True)),
                ('katametrimena', models.BigIntegerField(blank=True, null=True)),
                ('plithoskentrwn', models.BigIntegerField(db_column='plithosKentrwn')),
                ('posostosindiasmou', models.DecimalField(blank=True, db_column='posostoSindiasmou', decimal_places=2, max_digits=38, null=True)),
                ('posostokatametrimenwnkentrwn', models.DecimalField(blank=True, db_column='posostoKatametrimenwnKentrwn', decimal_places=2, max_digits=26, null=True)),
                ('sumvotesb', models.DecimalField(blank=True, db_column='sumVotesB', decimal_places=0, max_digits=32, null=True)),
                ('sinolab', models.DecimalField(blank=True, db_column='sinolaB', decimal_places=0, max_digits=32, null=True)),
                ('posostosindiasmoub', models.DecimalField(blank=True, db_column='posostoSindiasmouB', decimal_places=2, max_digits=38, null=True)),
                ('katametrimenab', models.BigIntegerField(blank=True, db_column='katametrimenaB', null=True)),
                ('posostokatametrimenwnkentrwnb', models.DecimalField(blank=True, db_column='posostoKatametrimenwnKentrwnB', decimal_places=2, max_digits=26, null=True)),
            ],
            options={
                'db_table': 'EKL_SUMPSIFODELTIASIND_VW',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EklSumpsifoiKenVw',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('eklid', models.IntegerField(db_column='eklID')),
                ('kentro', models.CharField(max_length=45)),
                ('kenid', models.IntegerField(db_column='kenID')),
                ('sumvotes', models.DecimalField(blank=True, db_column='sumVotes', decimal_places=0, max_digits=32, null=True)),
            ],
            options={
                'db_table': 'EKL_SUMPSIFOI_KEN_VW',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EklSumpsifoisimbAnalytikoAnaperifereia',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('eklid', models.IntegerField(db_column='eklID')),
                ('eidos', models.CharField(max_length=20)),
                ('simbid', models.IntegerField(db_column='simbID')),
                ('eklsimbkoin_simbid', models.IntegerField(blank=True, db_column='EKLSIMBKOIN_simbID', null=True)),
                ('surname', models.CharField(max_length=100)),
                ('firstname', models.CharField(max_length=100)),
                ('fathername', models.CharField(max_length=100)),
                ('perid', models.IntegerField(db_column='perID')),
                ('perifereia', models.CharField(max_length=100)),
                ('sumvotes', models.DecimalField(blank=True, db_column='sumVotes', decimal_places=0, max_digits=32, null=True)),
                ('sindid', models.IntegerField(blank=True, db_column='sindID', null=True)),
                ('sindiasmos', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'EKL_SUMPSIFOISIMB_ANALYTIKO_ANAPERIFEREIA',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EklSumpsifoisimbKoinVw',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('eklid', models.IntegerField(db_column='eklID')),
                ('simbid', models.IntegerField(db_column='simbID')),
                ('surname', models.CharField(max_length=100)),
                ('firstname', models.CharField(max_length=100)),
                ('fathername', models.CharField(max_length=100)),
                ('toposeklogisid', models.IntegerField(db_column='toposEklogisID')),
                ('toposeklogis', models.CharField(db_column='toposEklogis', max_length=100)),
                ('eidoskoinotitas', models.IntegerField(db_column='eidosKoinotitas')),
                ('sindid', models.IntegerField(blank=True, db_column='sindID', null=True)),
                ('sindiasmos', models.CharField(blank=True, max_length=100, null=True)),
                ('sumvotes', models.DecimalField(blank=True, db_column='sumVotes', decimal_places=0, max_digits=32, null=True)),
            ],
            options={
                'db_table': 'EKL_SUMPSIFOISIMB_KOIN_VW',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EklSumpsifoisimbPerVw',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('eklid', models.IntegerField(db_column='eklID')),
                ('simbid', models.IntegerField(db_column='simbID')),
                ('surname', models.CharField(max_length=100)),
                ('firstname', models.CharField(max_length=100)),
                ('fathername', models.CharField(max_length=100)),
                ('toposeklogisid', models.IntegerField(db_column='toposEklogisID')),
                ('toposeklogis', models.CharField(db_column='toposEklogis', max_length=100)),
                ('sindid', models.IntegerField(blank=True, db_column='sindID', null=True)),
                ('sindiasmos', models.CharField(blank=True, max_length=100, null=True)),
                ('sumvotes', models.DecimalField(blank=True, db_column='sumVotes', decimal_places=0, max_digits=32, null=True)),
            ],
            options={
                'db_table': 'EKL_SUMPSIFOISIMB_PER_VW',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EklSumpsifoisimbVw',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('eklid', models.IntegerField(db_column='eklID')),
                ('simbid', models.IntegerField(db_column='simbID')),
                ('surname', models.CharField(max_length=100)),
                ('firstname', models.CharField(max_length=100)),
                ('fathername', models.CharField(max_length=100)),
                ('toposeklogisid', models.IntegerField(db_column='toposEklogisID')),
                ('toposeklogis', models.CharField(db_column='toposEklogis', max_length=100)),
                ('eidoskoinotitas', models.IntegerField(blank=True, db_column='eidosKoinotitas', null=True)),
                ('sindid', models.IntegerField(blank=True, db_column='sindID', null=True)),
                ('sindiasmos', models.CharField(blank=True, max_length=100, null=True)),
                ('sumvotes', models.DecimalField(blank=True, db_column='sumVotes', decimal_places=0, max_digits=32, null=True)),
            ],
            options={
                'db_table': 'EKL_SUMPSIFOISIMB_VW',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Edres',
            fields=[
                ('edrid', models.AutoField(db_column='edrID', primary_key=True, serialize=False)),
                ('descr', models.CharField(max_length=45, verbose_name='Περιγραφή')),
                ('sinoloedrwn', models.IntegerField(db_column='sinoloEdrwn', verbose_name='Σύνολο εδρών')),
                ('edresprwtou', models.IntegerField(db_column='edresPrwtou', verbose_name='Έδρες Πρώτου')),
                ('edresypoloipwn', models.IntegerField(db_column='edresYpoloipwn', verbose_name='Έδρες Υπολοίπων')),
            ],
            options={
                'db_table': 'EDRES',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Edreskoin',
            fields=[
                ('edrid', models.AutoField(db_column='edrID', primary_key=True, serialize=False)),
                ('descr', models.CharField(max_length=100)),
                ('sinolo', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'EDRESKOIN',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Eklogestbl',
            fields=[
                ('eklid', models.AutoField(db_column='eklID', primary_key=True, serialize=False)),
                ('descr', models.CharField(max_length=100, unique=True)),
                ('dateofelection', models.DateTimeField(blank=True, db_column='dateOfElection', null=True)),
                ('dimos', models.CharField(blank=True, max_length=100)),
                ('visible', models.IntegerField(db_column='visible', default=1)),
                ('defaultelection', models.IntegerField(db_column='defaultElection', default=1)),
                ('edrid', models.ForeignKey(db_column='edrID', on_delete=django.db.models.deletion.DO_NOTHING, to='Elections.Edres')),
            ],
            options={
                'db_table': 'EKLOGESTBL',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Eklper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eklid', models.ForeignKey(db_column='eklID', on_delete=django.db.models.deletion.DO_NOTHING, to='Elections.Eklogestbl')),
            ],
            options={
                'db_table': 'EKLPER',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Eklperkoin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edrid', models.ForeignKey(blank=True, db_column='edrID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Elections.Edreskoin')),
                ('eklid', models.ForeignKey(db_column='eklID', on_delete=django.db.models.deletion.DO_NOTHING, to='Elections.Eklogestbl')),
            ],
            options={
                'db_table': 'EKLPERKOIN',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Eklsimbkoin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eklid', models.ForeignKey(db_column='eklID', on_delete=django.db.models.deletion.DO_NOTHING, to='Elections.Eklogestbl')),
            ],
            options={
                'db_table': 'EKLSIMBKOIN',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Eklsimbper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eklid', models.ForeignKey(db_column='eklID', on_delete=django.db.models.deletion.DO_NOTHING, to='Elections.Eklogestbl')),
            ],
            options={
                'db_table': 'EKLSIMBPER',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Eklsind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aa', models.CharField(max_length=45)),
                ('edresa', models.IntegerField(db_column='edresA', default=0)),
                ('edresa_ypol', models.IntegerField(db_column='edresA_Ypol', default=0)),
                ('edresa_teliko', models.IntegerField(db_column='edresA_Teliko', default=0)),
                ('edresb', models.IntegerField(db_column='edresB', default=0)),
                ('ypol', models.IntegerField(default=0)),
                ('eklid', models.ForeignKey(db_column='eklID', on_delete=django.db.models.deletion.DO_NOTHING, to='Elections.Eklogestbl')),
            ],
            options={
                'db_table': 'EKLSIND',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Eklsindkoin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aa', models.CharField(blank=True, max_length=45)),
                ('proedros', models.CharField(blank=True, max_length=100)),
                ('edresk', models.IntegerField(db_column='edresK', default=0)),
                ('edresk_ypol', models.IntegerField(db_column='edresK_Ypol', default=0)),
                ('edresk_teliko', models.IntegerField(db_column='edresK_Teliko', default=0)),
                ('ypol', models.IntegerField(default=0)),
                ('checkfordraw', models.IntegerField(db_column='checkForDraw', default=0)),
                ('eklid', models.ForeignKey(db_column='eklID', on_delete=django.db.models.deletion.DO_NOTHING, to='Elections.Eklogestbl')),
            ],
            options={
                'db_table': 'EKLSINDKOIN',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Eklsindsimb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aa', models.CharField(blank=True, max_length=45)),
                ('eklid', models.ForeignKey(db_column='eklID', on_delete=django.db.models.deletion.DO_NOTHING, to='Elections.Eklogestbl')),
            ],
            options={
                'db_table': 'EKLSINDSIMB',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Kentra',
            fields=[
                ('kenid', models.AutoField(db_column='kenID', primary_key=True, serialize=False)),
                ('descr', models.CharField(max_length=45)),
                ('eggegrammenoia', models.IntegerField(db_column='eggegrammenoiA', default=0)),
                ('psifisana', models.IntegerField(db_column='psifisanA', default=0)),
                ('egkiraa', models.IntegerField(db_column='egkiraA', default=0)),
                ('akiraa', models.IntegerField(db_column='akiraA', default=0)),
                ('lefkaa', models.IntegerField(db_column='lefkaA', default=0)),
                ('sinoloakiralefkaa', models.IntegerField(db_column='sinoloAkiraLefkaA', default=0)),
                ('comments', models.CharField(blank=True, max_length=250)),
                ('eggegrammenoib', models.IntegerField(db_column='eggegrammenoiB', default=0)),
                ('psifisanb', models.IntegerField(db_column='psifisanB', default=0)),
                ('egkirab', models.IntegerField(db_column='egkiraB', default=0)),
                ('akirab', models.IntegerField(db_column='akiraB', default=0)),
                ('lefkab', models.IntegerField(db_column='lefkaB', default=0)),
                ('sinoloakiralefkab', models.IntegerField(db_column='sinoloAkiraLefkaB', default=0)),
                ('eggegrammenoik', models.IntegerField(db_column='eggegrammenoiK', default=0)),
                ('psifisank', models.IntegerField(db_column='psifisanK', default=0)),
                ('egkirak', models.IntegerField(db_column='egkiraK', default=0)),
                ('akirak', models.IntegerField(db_column='akiraK', default=0)),
                ('lefkak', models.IntegerField(db_column='lefkaK', default=0)),
                ('sinoloakiralefkak', models.IntegerField(db_column='sinoloAkiraLefkaK', default=0)),
                ('eklid', models.ForeignKey(db_column='eklID', on_delete=django.db.models.deletion.DO_NOTHING, to='Elections.Eklogestbl')),
            ],
            options={
                'db_table': 'KENTRA',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Koinotites',
            fields=[
                ('koinid', models.AutoField(db_column='koinID', primary_key=True, serialize=False)),
                ('descr', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'KOINOTITES',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Perifereies',
            fields=[
                ('perid', models.AutoField(db_column='perID', primary_key=True, serialize=False)),
                ('descr', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'PERIFEREIES',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Psifodeltia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votesa', models.IntegerField(db_column='votesA', default=0)),
                ('votesb', models.IntegerField(db_column='votesB', default=0)),
                ('votesk', models.IntegerField(db_column='votesK', default=0)),
                ('kenid', models.ForeignKey(db_column='kenID', on_delete=django.db.models.deletion.DO_NOTHING, to='Elections.Kentra')),
            ],
            options={
                'db_table': 'PSIFODELTIA',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Psifoi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votes', models.IntegerField(default=0)),
                ('kenid', models.ForeignKey(db_column='kenID', on_delete=django.db.models.deletion.DO_NOTHING, to='Elections.Kentra')),
            ],
            options={
                'db_table': 'PSIFOI',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Simbouloi',
            fields=[
                ('simbid', models.AutoField(db_column='simbID', primary_key=True, serialize=False)),
                ('surname', models.CharField(max_length=100)),
                ('firstname', models.CharField(max_length=100)),
                ('fathername', models.CharField(max_length=100)),
                ('comments', models.CharField(blank=True, max_length=250)),
            ],
            options={
                'db_table': 'SIMBOULOI',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Sindiasmoi',
            fields=[
                ('sindid', models.IntegerField(db_column='sindID', primary_key=True, serialize=False)),
                ('descr', models.CharField(max_length=100)),
                ('shortdescr', models.CharField(db_column='shortDescr', max_length=50)),
                ('photo', models.ImageField(db_column='photo', null=True, upload_to='')),
                ('eidos', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'SINDIASMOI',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Sistima',
            fields=[
                ('sisid', models.AutoField(db_column='sisID', primary_key=True, serialize=False)),
                ('descr', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'SISTIMA',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Typeofkoinotita',
            fields=[
                ('tpkid', models.IntegerField(db_column='tpkID', primary_key=True, serialize=False)),
                ('descr', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'TYPEOFKOINOTITA',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='psifoi',
            name='simbid',
            field=models.ForeignKey(db_column='simbID', on_delete=django.db.models.deletion.DO_NOTHING, to='Elections.Simbouloi'),
        ),
        migrations.AddField(
            model_name='psifodeltia',
            name='sindid',
            field=models.ForeignKey(db_column='sindID', on_delete=django.db.models.deletion.DO_NOTHING, to='Elections.Sindiasmoi'),
        ),
        migrations.AddField(
            model_name='koinotites',
            name='eidos',
            field=models.ForeignKey(db_column='eidos', on_delete=django.db.models.deletion.DO_NOTHING, to='Elections.Typeofkoinotita'),
        ),
        migrations.AddField(
            model_name='kentra',
            name='koinid',
            field=models.ForeignKey(db_column='koinID', on_delete=django.db.models.deletion.DO_NOTHING, to='Elections.Koinotites'),
        ),
        migrations.AddField(
            model_name='kentra',
            name='perid',
            field=models.ForeignKey(db_column='perID', on_delete=django.db.models.deletion.DO_NOTHING, to='Elections.Perifereies'),
        ),
        migrations.AddField(
            model_name='eklsindsimb',
            name='simbid',
            field=models.ForeignKey(db_column='simbID', on_delete=django.db.models.deletion.DO_NOTHING, to='Elections.Simbouloi'),
        ),
        migrations.AddField(
            model_name='eklsindsimb',
            name='sindid',
            field=models.ForeignKey(blank=True, db_column='sindID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Elections.Sindiasmoi'),
        ),
        migrations.AddField(
            model_name='eklsindkoin',
            name='koinid',
            field=models.ForeignKey(db_column='koinID', on_delete=django.db.models.deletion.DO_NOTHING, to='Elections.Koinotites'),
        ),
        migrations.AddField(
            model_name='eklsindkoin',
            name='sindid',
            field=models.ForeignKey(db_column='sindID', on_delete=django.db.models.deletion.DO_NOTHING, to='Elections.Sindiasmoi'),
        ),
        migrations.AddField(
            model_name='eklsind',
            name='sindid',
            field=models.ForeignKey(db_column='sindID', on_delete=django.db.models.deletion.DO_NOTHING, to='Elections.Sindiasmoi'),
        ),
        migrations.AddField(
            model_name='eklsimbper',
            name='perid',
            field=models.ForeignKey(db_column='perID', on_delete=django.db.models.deletion.DO_NOTHING, to='Elections.Perifereies'),
        ),
        migrations.AddField(
            model_name='eklsimbper',
            name='simbid',
            field=models.ForeignKey(db_column='simbID', on_delete=django.db.models.deletion.DO_NOTHING, to='Elections.Simbouloi'),
        ),
        migrations.AddField(
            model_name='eklsimbkoin',
            name='koinid',
            field=models.ForeignKey(db_column='koinID', on_delete=django.db.models.deletion.DO_NOTHING, to='Elections.Koinotites'),
        ),
        migrations.AddField(
            model_name='eklsimbkoin',
            name='simbid',
            field=models.ForeignKey(db_column='simbID', on_delete=django.db.models.deletion.DO_NOTHING, to='Elections.Simbouloi'),
        ),
        migrations.AddField(
            model_name='eklperkoin',
            name='koinid',
            field=models.ForeignKey(db_column='koinID', on_delete=django.db.models.deletion.DO_NOTHING, to='Elections.Koinotites'),
        ),
        migrations.AddField(
            model_name='eklperkoin',
            name='perid',
            field=models.ForeignKey(db_column='perID', on_delete=django.db.models.deletion.DO_NOTHING, to='Elections.Perifereies'),
        ),
        migrations.AddField(
            model_name='eklper',
            name='perid',
            field=models.ForeignKey(db_column='perID', on_delete=django.db.models.deletion.DO_NOTHING, to='Elections.Perifereies'),
        ),
        migrations.AddField(
            model_name='eklogestbl',
            name='sisid',
            field=models.ForeignKey(db_column='sisID', on_delete=django.db.models.deletion.DO_NOTHING, to='Elections.Sistima'),
        ),
        migrations.AlterUniqueTogether(
            name='psifoi',
            unique_together={('simbid', 'kenid')},
        ),
        migrations.AlterUniqueTogether(
            name='psifodeltia',
            unique_together={('sindid', 'kenid')},
        ),
        migrations.AlterUniqueTogether(
            name='kentra',
            unique_together={('descr', 'eklid')},
        ),
        migrations.AlterUniqueTogether(
            name='eklsindsimb',
            unique_together={('eklid', 'simbid')},
        ),
        migrations.AlterUniqueTogether(
            name='eklsindkoin',
            unique_together={('eklid', 'sindid', 'koinid')},
        ),
        migrations.AlterUniqueTogether(
            name='eklsind',
            unique_together={('eklid', 'sindid')},
        ),
        migrations.AlterUniqueTogether(
            name='eklsimbper',
            unique_together={('eklid', 'simbid')},
        ),
        migrations.AlterUniqueTogether(
            name='eklsimbkoin',
            unique_together={('eklid', 'simbid')},
        ),
        migrations.AlterUniqueTogether(
            name='eklperkoin',
            unique_together={('eklid', 'koinid')},
        ),
        migrations.AlterUniqueTogether(
            name='eklper',
            unique_together={('eklid', 'perid')},
        ),
    ]
