# Generated by Django 2.1 on 2019-03-03 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Elections', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eklsimbkoin',
            name='koinid',
            field=models.ForeignKey(db_column='koinID', on_delete=django.db.models.deletion.CASCADE, to='Elections.Koinotites'),
        ),
        migrations.AlterField(
            model_name='eklsimbkoin',
            name='simbid',
            field=models.ForeignKey(db_column='simbID', on_delete=django.db.models.deletion.CASCADE, to='Elections.Simbouloi'),
        ),
        migrations.AlterField(
            model_name='eklsimbper',
            name='perid',
            field=models.ForeignKey(db_column='perID', on_delete=django.db.models.deletion.CASCADE, to='Elections.Perifereies'),
        ),
        migrations.AlterField(
            model_name='eklsimbper',
            name='simbid',
            field=models.ForeignKey(db_column='simbID', on_delete=django.db.models.deletion.CASCADE, to='Elections.Simbouloi'),
        ),
    ]
