# Generated by Django 2.1 on 2019-02-26 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Elections', '0002_auto_20190225_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='eklsindkoin',
            name='descr',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='eklsindkoin',
            name='photofield',
            field=models.ImageField(blank=True, null=True, upload_to='sindiasmoi'),
        ),
        migrations.AddField(
            model_name='eklsindkoin',
            name='shortdescr',
            field=models.CharField(blank=True, db_column='shortDescr', max_length=50, null=True),
        ),
    ]
