# Generated by Django 2.1 on 2018-10-31 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Elections', '0003_simbouloi_photofield'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sindiasmoi',
            old_name='photo',
            new_name='photofield',
        ),
    ]
