# Generated by Django 2.1 on 2018-08-28 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Elections', '0003_auto_20180828_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sindiasmoi',
            name='photo',
            field=models.ImageField(blank=True, db_column='photo', null=True, upload_to=''),
        ),
    ]
