# Generated by Django 2.1 on 2019-05-01 19:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Elections', '0003_historicalpsifodeltia'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalPsifoi',
            fields=[
                ('id', models.IntegerField(blank=True, db_column='id', db_index=True)),
                ('votes', models.IntegerField(default=0)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('kenid', models.ForeignKey(blank=True, db_column='kenID', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Elections.Kentra')),
                ('simbid', models.ForeignKey(blank=True, db_column='simbID', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Elections.Simbouloi')),
            ],
            options={
                'verbose_name': 'historical psifoi',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
