# Generated by Django 2.1 on 2018-10-31 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Elections', '0004_auto_20181031_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sindiasmoi',
            name='photofield',
            field=models.ImageField(blank=True, null=True, upload_to='sindiasmoi'),
        ),
    ]
