# Generated by Django 2.1 on 2018-08-28 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Elections', '0004_auto_20180828_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eklsind',
            name='id',
            field=models.AutoField(db_column='id', primary_key=True, serialize=False),
        ),
    ]
