# Generated by Django 2.1 on 2019-05-30 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Elections', '0004_historicalpsifoi'),
    ]

    operations = [
        migrations.CreateModel(
            name='EklKatametrimenaPsifoiKoinotitesOnlyVw',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('eklid', models.IntegerField(db_column='eklID')),
                ('katametrimena_psifoi', models.BigIntegerField()),
            ],
            options={
                'db_table': 'EKL_KATAMETRIMENA_PSIFOI_KOINOTHTES_ONLY',
                'managed': False,
            },
        ),
    ]
