# Generated by Django 2.1 on 2018-08-29 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Elections', '0005_auto_20180828_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sindiasmoi',
            name='photo',
            field=models.ImageField(blank=True, db_column='photo', null=True, upload_to='sindiasmoi/'),
        ),
    ]
