# Generated by Django 2.1 on 2018-10-31 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Elections', '0005_auto_20181031_1124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simbouloi',
            name='photofield',
        ),
    ]
