# Generated by Django 2.1 on 2018-08-30 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Elections', '0006_auto_20180829_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eklsind',
            name='sindid',
            field=models.ForeignKey(db_column='sindID', on_delete=django.db.models.deletion.CASCADE, to='Elections.Sindiasmoi'),
        ),
    ]
