# Generated by Django 2.1 on 2018-08-31 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Elections', '0008_auto_20180831_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eklper',
            name='perid',
            field=models.ForeignKey(db_column='perID', on_delete=django.db.models.deletion.CASCADE, to='Elections.Perifereies'),
        ),
    ]
