# Generated by Django 2.1 on 2018-09-02 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Elections', '0009_auto_20180831_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eklperkoin',
            name='edrid',
            field=models.ForeignKey(blank=True, db_column='edrID', null=True, on_delete=django.db.models.deletion.CASCADE, to='Elections.Edreskoin'),
        ),
        migrations.AlterField(
            model_name='eklperkoin',
            name='koinid',
            field=models.ForeignKey(db_column='koinID', on_delete=django.db.models.deletion.CASCADE, to='Elections.Koinotites'),
        ),
        migrations.AlterField(
            model_name='eklperkoin',
            name='perid',
            field=models.ForeignKey(db_column='perID', on_delete=django.db.models.deletion.CASCADE, to='Elections.Perifereies'),
        ),
        migrations.AlterField(
            model_name='eklsindkoin',
            name='aa',
            field=models.CharField(max_length=45),
        ),
    ]
