# Generated by Django 2.1 on 2018-09-07 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Elections', '0010_auto_20180902_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psifodeltia',
            name='id',
            field=models.AutoField(db_column='id', primary_key=True, serialize=False),
        ),
    ]
