# Generated by Django 2.1 on 2018-09-09 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Elections', '0012_auto_20180907_2300'),
    ]

    operations = [
        migrations.CreateModel(
            name='EklSumpsifoisimbWithIdVw',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('eklid', models.IntegerField(db_column='eklID')),
                ('simbid', models.IntegerField(db_column='simbID')),
                ('surname', models.CharField(max_length=100)),
                ('firstname', models.CharField(max_length=100)),
                ('fathername', models.CharField(max_length=100)),
                ('toposeklogisid', models.IntegerField(db_column='toposEklogisID')),
                ('toposeklogis', models.CharField(db_column='toposEklogis', max_length=100)),
                ('eidoskoinotitas', models.IntegerField(blank=True, db_column='eidosKoinotitas', null=True)),
                ('sindid', models.IntegerField(blank=True, db_column='sindID', null=True)),
                ('sindiasmos', models.CharField(blank=True, max_length=100, null=True)),
                ('sumvotes', models.DecimalField(blank=True, db_column='sumVotes', decimal_places=0, max_digits=32, null=True)),
            ],
            options={
                'db_table': 'EKL_SUMPSIFOISIMB_WITHID_VW',
                'managed': False,
            },
        ),
    ]
