# Generated by Django 2.1 on 2018-09-09 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Elections', '0013_eklsumpsifoisimbwithidvw'),
    ]

    operations = [
        migrations.CreateModel(
            name='EklallsimbVw',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('eklid', models.IntegerField(db_column='eklID')),
                ('simbid', models.IntegerField(db_column='simbID')),
                ('surname', models.CharField(max_length=100)),
                ('firstname', models.CharField(max_length=100)),
                ('fathername', models.CharField(max_length=100)),
                ('toposeklogisid', models.IntegerField(db_column='toposEklogisID')),
                ('toposeklogis', models.CharField(db_column='toposEklogis', max_length=100)),
                ('eidoskoinotitas', models.IntegerField(blank=True, db_column='eidosKoinotitas', null=True)),
                ('sindid', models.IntegerField(blank=True, db_column='sindID', null=True)),
                ('sindiasmos', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'EKL_ALLSIMB_VW',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='eklsindsimb',
            name='simbid',
            field=models.ForeignKey(db_column='simbID', on_delete=django.db.models.deletion.CASCADE, to='Elections.Simbouloi'),
        ),
        migrations.AlterField(
            model_name='eklsindsimb',
            name='sindid',
            field=models.ForeignKey(blank=True, db_column='sindID', null=True, on_delete=django.db.models.deletion.CASCADE, to='Elections.Sindiasmoi'),
        ),
    ]
