# Generated by Django 2.1 on 2018-09-19 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Elections', '0015_auto_20180910_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psifoi',
            name='id',
            field=models.AutoField(db_column='id', primary_key=True, serialize=False),
        ),
    ]
