# Generated by Django 2.1 on 2018-09-23 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Elections', '0016_auto_20180919_0818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edres',
            name='edrid',
            field=models.AutoField(db_column='edrID', db_index=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='edreskoin',
            name='edrid',
            field=models.AutoField(db_column='edrID', db_index=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='eklogestbl',
            name='eklid',
            field=models.AutoField(db_column='eklID', db_index=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='kentra',
            name='kenid',
            field=models.AutoField(db_column='kenID', db_index=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='koinotites',
            name='koinid',
            field=models.AutoField(db_column='koinID', db_index=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='perifereies',
            name='perid',
            field=models.AutoField(db_column='perID', db_index=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='simbouloi',
            name='fathername',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='simbouloi',
            name='firstname',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='simbouloi',
            name='simbid',
            field=models.AutoField(db_column='simbID', db_index=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='simbouloi',
            name='surname',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sindiasmoi',
            name='sindid',
            field=models.AutoField(db_column='sindID', db_index=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sistima',
            name='sisid',
            field=models.AutoField(db_column='sisID', db_index=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='typeofkoinotita',
            name='tpkid',
            field=models.IntegerField(db_column='tpkID', db_index=True, primary_key=True, serialize=False),
        ),
    ]
