# Generated by Django 2.1 on 2018-10-11 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Elections', '0017_auto_20180923_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sindiasmoi',
            name='photo',
            field=models.ImageField(blank=True, db_column='photo', default='elections.jpg', null=True, upload_to='sindiasmoi'),
        ),
    ]
