# Generated by Django 2.1 on 2018-10-14 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Elections', '0018_auto_20181011_0954'),
    ]

    operations = [
        migrations.CreateModel(
            name='EklSumpsifodeltiasindKenTopikoiOnlyVw',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('kentro', models.CharField(max_length=45)),
                ('votes', models.IntegerField()),
                ('votesb', models.IntegerField(db_column='votesB')),
                ('votesk', models.IntegerField(db_column='votesK')),
                ('sindiasmos', models.CharField(max_length=100)),
                ('eidos', models.IntegerField(db_column='eidos')),
            ],
            options={
                'db_table': 'EKL_SUMPSIFODELTIASINDTOPIKOIONLY_KEN_VW',
                'managed': False,
            },
        ),
    ]
