# Generated by Django 2.1 on 2018-10-16 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Elections', '0019_eklsumpsifodeltiasindkentopikoionlyvw'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eklsindkoin',
            name='koinid',
            field=models.ForeignKey(db_column='koinID', on_delete=django.db.models.deletion.CASCADE, to='Elections.Koinotites'),
        ),
        migrations.AlterField(
            model_name='eklsindkoin',
            name='sindid',
            field=models.ForeignKey(db_column='sindID', on_delete=django.db.models.deletion.CASCADE, to='Elections.Sindiasmoi'),
        ),
    ]
