# Generated by Django 2.1 on 2018-10-20 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Elections', '0020_auto_20181017_0122'),
    ]

    operations = [
        migrations.CreateModel(
            name='EklSumpsifodeltiasindKoinVw',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('sindiasmos', models.CharField(max_length=100)),
                ('koinid', models.IntegerField(db_column='koinID')),
                ('descr', models.CharField(db_column='descr', max_length=100)),
                ('eidos', models.IntegerField(db_column='eidos')),
                ('sumasindiasmou', models.DecimalField(blank=True, db_column='sumASindiasmou', decimal_places=0, max_digits=32, null=True)),
                ('sumbsindiasmou', models.DecimalField(blank=True, db_column='sumBSindiasmou', decimal_places=0, max_digits=32, null=True)),
                ('sumksindiasmou', models.DecimalField(blank=True, db_column='sumKSindiasmou', decimal_places=0, max_digits=32, null=True)),
                ('sumkkoinotitas', models.DecimalField(blank=True, db_column='sumkKoinotitas', decimal_places=0, max_digits=32, null=True)),
            ],
            options={
                'db_table': 'EKL_SUMPSIFODELTIASIND_KOIN_VW',
                'managed': False,
            },
        ),
    ]
