# Generated by Django 2.1 on 2018-10-22 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Elections', '0021_eklsumpsifodeltiasindkoinvw'),
    ]

    operations = [
        migrations.CreateModel(
            name='EklSumpsifoisimbPerLightVw',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('sumvotes', models.DecimalField(blank=True, db_column='sumVotes', decimal_places=0, max_digits=32, null=True)),
            ],
            options={
                'db_table': 'EKL_SUMPSIFOISIMBPER_LIGHT_VW',
                'managed': False,
            },
        ),
    ]
